<?php
/*
 * TransmitMessageLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TransmitMessageLib\Models;

use JsonSerializable;

/**
 *Add contacts into a specific contact list
 */
class AddToContactList implements JsonSerializable
{
    /**
     * IDs of Contact to be added to the list
     * @required
     * @maps contact_ids
     * @var array $contactIds public property
     */
    public $contactIds;

    /**
     * Constructor to set initial or default values of member properties
     * @param array $contactIds Initialization value for $this->contactIds
     */
    public function __construct()
    {
        if (1 == func_num_args()) {
            $this->contactIds = func_get_arg(0);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['contact_ids'] = $this->contactIds;

        return $json;
    }
}
