<?php
/*
 * TransmitMessageLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TransmitMessageLib\Models;

use JsonSerializable;

/**
 *Contact Field
 */
class ContactField implements JsonSerializable
{
    /**
     * Custom field name: the key will be constructed from the name automatically
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * Field type: text, number, date, list, multi
     * @required
     * @var string $type public property
     */
    public $type;

    /**
     * Number of decimal points to display when type is 'number'
     * @var string|null $decimals public property
     */
    public $decimals;

    /**
     * Values to use when the type is 'list' or 'multi'
     * @maps list_values
     * @var array|null $listValues public property
     */
    public $listValues;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $name       Initialization value for $this->name
     * @param string $type       Initialization value for $this->type
     * @param string $decimals   Initialization value for $this->decimals
     * @param array  $listValues Initialization value for $this->listValues
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->name       = func_get_arg(0);
            $this->type       = func_get_arg(1);
            $this->decimals   = func_get_arg(2);
            $this->listValues = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']        = $this->name;
        $json['type']        = $this->type;
        $json['decimals']    = $this->decimals;
        $json['list_values'] = $this->listValues;

        return $json;
    }
}
