<?php
/*
 * TransmitMessageLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TransmitMessageLib\Models;

use JsonSerializable;

/**
 *Contact List
 */
class ContactList implements JsonSerializable
{
    /**
     * List name
     * @required
     * @var string $name public property
     */
    public $name;

    /**
     * List Description
     * @var string|null $body public property
     */
    public $body;

    /**
     * A list of contact filters to create a dynamic list with
     * @var array|null $filters public property
     */
    public $filters;

    /**
     * Flag to make this list static instead of dynamic
     * @required
     * @maps static
     * @var bool $mstatic public property
     */
    public $mstatic;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $name    Initialization value for $this->name
     * @param string $body    Initialization value for $this->body
     * @param array  $filters Initialization value for $this->filters
     * @param bool   $mstatic Initialization value for $this->mstatic
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->name    = func_get_arg(0);
            $this->body    = func_get_arg(1);
            $this->filters = func_get_arg(2);
            $this->mstatic = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['name']    = $this->name;
        $json['body']    = $this->body;
        $json['filters'] = $this->filters;
        $json['static']  = $this->mstatic;

        return $json;
    }
}
