<?php
/*
 * TransmitMessageLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TransmitMessageLib\Models;

use JsonSerializable;

/**
 *MMS Campaign details
 */
class MMSCampaign implements JsonSerializable
{
    /**
     * Contact List ID
     * @required
     * @maps list_id
     * @var string $listId public property
     */
    public $listId;

    /**
     * Sender ID
     * @required
     * @var string $sender public property
     */
    public $sender;

    /**
     * MMS Subject (Optional)
     * @var string|null $subject public property
     */
    public $subject;

    /**
     * MMS text content (Optional)
     * @required
     * @var string $body public property
     */
    public $body;

    /**
     * List of Image URLs
     * @required
     * @maps resource_urls
     * @var array $resourceUrls public property
     */
    public $resourceUrls;

    /**
     * Date on which the message is sent
     * @maps send_date
     * @var string|null $sendDate public property
     */
    public $sendDate;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $listId       Initialization value for $this->listId
     * @param string $sender       Initialization value for $this->sender
     * @param string $subject      Initialization value for $this->subject
     * @param string $body         Initialization value for $this->body
     * @param array  $resourceUrls Initialization value for $this->resourceUrls
     * @param string $sendDate     Initialization value for $this->sendDate
     */
    public function __construct()
    {
        if (6 == func_num_args()) {
            $this->listId       = func_get_arg(0);
            $this->sender       = func_get_arg(1);
            $this->subject      = func_get_arg(2);
            $this->body         = func_get_arg(3);
            $this->resourceUrls = func_get_arg(4);
            $this->sendDate     = func_get_arg(5);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['list_id']       = $this->listId;
        $json['sender']        = $this->sender;
        $json['subject']       = $this->subject;
        $json['body']          = $this->body;
        $json['resource_urls'] = $this->resourceUrls;
        $json['send_date']     = $this->sendDate;

        return $json;
    }
}
