<?php
/*
 * TransmitMessageLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TransmitMessageLib\Models;

use JsonSerializable;

/**
 *Phone Number
 */
class PhoneNumber implements JsonSerializable
{
    /**
     * Phone number to be formatted
     * @required
     * @var string $number public property
     */
    public $number;

    /**
     * ISO2 country code
     * @required
     * @maps country_code
     * @var string $countryCode public property
     */
    public $countryCode;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $number      Initialization value for $this->number
     * @param string $countryCode Initialization value for $this->countryCode
     */
    public function __construct()
    {
        if (2 == func_num_args()) {
            $this->number      = func_get_arg(0);
            $this->countryCode = func_get_arg(1);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['number']       = $this->number;
        $json['country_code'] = $this->countryCode;

        return $json;
    }
}
