<?php
/*
 * TransmitMessageLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TransmitMessageLib\Models;

use JsonSerializable;

/**
 *SMS details
 */
class SMS implements JsonSerializable
{
    /**
     * Sender ID for the campaign
     * @required
     * @var string $sender public property
     */
    public $sender;

    /**
     * Recipient mobile number
     * @required
     * @var string $recipient public property
     */
    public $recipient;

    /**
     * Message content
     * @required
     * @var string $message public property
     */
    public $message;

    /**
     * Date on which the message is sent
     * @maps send_date
     * @var string|null $sendDate public property
     */
    public $sendDate;

    /**
     * Constructor to set initial or default values of member properties
     * @param string $sender    Initialization value for $this->sender
     * @param string $recipient Initialization value for $this->recipient
     * @param string $message   Initialization value for $this->message
     * @param string $sendDate  Initialization value for $this->sendDate
     */
    public function __construct()
    {
        if (4 == func_num_args()) {
            $this->sender    = func_get_arg(0);
            $this->recipient = func_get_arg(1);
            $this->message   = func_get_arg(2);
            $this->sendDate  = func_get_arg(3);
        }
    }


    /**
     * Encode this object to JSON
     */
    public function jsonSerialize()
    {
        $json = array();
        $json['sender']    = $this->sender;
        $json['recipient'] = $this->recipient;
        $json['message']   = $this->message;
        $json['send_date'] = $this->sendDate;

        return $json;
    }
}
