<?php
/*
 * TransmitMessageLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TransmitMessageLib;

/**
 * Environments available for API
 */
class Environments
{
    /**
     * This environment connects to the LIVE TransmitMessage service
     */
    const PRODUCTION = "production";
}
