<?php
/*
 * TransmitMessageLib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */

namespace TransmitMessageLib;

use TransmitMessageLib\Controllers;

/**
 * TransmitMessageLib client class
 */
class TransmitMessageClient
{
    /**
     * Constructor with authentication and configuration parameters
     */
    public function __construct(
        $xApiKey = null
    ) {
        Configuration::$xApiKey = $xApiKey ? $xApiKey : Configuration::$xApiKey;
    }
    /**
     * Singleton access to Contacts controller
     * @return Controllers\ContactsController The *Singleton* instance
     */
    public function getContacts()
    {
        return Controllers\ContactsController::getInstance();
    }
    /**
     * Singleton access to Accounts controller
     * @return Controllers\AccountsController The *Singleton* instance
     */
    public function getAccounts()
    {
        return Controllers\AccountsController::getInstance();
    }
    /**
     * Singleton access to MMS controller
     * @return Controllers\MMSController The *Singleton* instance
     */
    public function getMMS()
    {
        return Controllers\MMSController::getInstance();
    }
    /**
     * Singleton access to SMS controller
     * @return Controllers\SMSController The *Singleton* instance
     */
    public function getSMS()
    {
        return Controllers\SMSController::getInstance();
    }
}
